#server:
#   port: 8090

spring:
#   database:
#       driverClassName: "com.mysql.jdbc.Driver"
   datasource:
      url: "jdbc:mysql://db:3306/mbaDB?useSSL=false&allowPublicKeyRetrieval=true"  
      username: "root"
      password: "root1234" 
      testWhileIdle: "true"
      validationQuery: "SELECT 1"
      continue-on-error: "false"   
   jpa:
      show-sql: "true"
      properties: 
         hibernate:
            dialect: "org.hibernate.dialect.MySQLDialect"

